FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
    TienKung_Velocity:
      id: 4
      type: RLBase
    Squat:
      id: 101
      type: Squat
  Passive:
    transitions:
      FixStand: LT + up.on_pressed
      Squat: RB + Y.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,
      3,3,3,3,3,3,3,
    ]
  FixStand:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
      TienKung_Velocity: LT + Y.on_pressed
      Squat: RB + Y.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity:
    transitions:
      Passive: LT + B.on_pressed
    policy_dir: config/policy/unitree_g1_23dof_velocity/2025-12-28_11-32-28
  TienKung_Velocity:
    transitions:
      Passive: LT + B.on_pressed
    policy_dir: config/policy/TienKung/2025-12-27_18-35-04
  Squat:
    transitions:
      # FixStand: LT + up.on_pressed
      # Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    # policy_dir: config/policy/lyenbot_leg_squat/2026-01-15_20-32-26/
    policy_dir: config/policy/g123dof_cam_squat/2026-01-31_09-31-43/
    # policy_dir: config/policy/lyenbotleg_unitree_squat/2026-01-17_10-43-21

